---

issues:
  exclude-rules:
    - path: '_test[.]go'
      linters:
        - goerr113
      text: do not define dynamic errors
linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - goerr113
    - gosec
    - gosimple
    - ineffassign
    - interfacebloat
    - makezero
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - reassign
    - staticcheck
    - tenv
    - testpackage
    - typecheck
    - unparam
    - unused
linters-settings:
  errcheck:
    check-type-assertions: true
  errorlint:
    asserts: true
  exhaustive:
    default-signifies-exhaustive: true
